### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by KSKOP69** [Pranav-Saraswat/YukkiMusicFork#22]
![photo_2023-12-02_16-26-04](https://github.com/Pranav-Saraswat/Testing-Alpha/assets/123794242/021e2891-d2d5-41f8-ac1c-6ac964e19ab9)

**Comment by KSKOP69** [comment]
> ??

![photo_2023-12-02_17-07-35](https://github.com/Pranav-Saraswat/Testing-Alpha/assets/123794242/76732b6b-e470-48f7-a52e-dd7f4f705d5d)

**Comment by Pranav-Saraswat** [comment]
this is bug seriously?

**Comment by KSKOP69** [comment]
> this is bug seriously?

![photo_2023-12-02_17-14-22](https://github.com/Pranav-Saraswat/Testing-Alpha/assets/123794242/5ed38559-97ea-4687-8e3a-a6df5b6b1108)

**Comment by KSKOP69** [comment]
> this is bug seriously?

i am reporting a bug in other repo. i mistakenly given the title bug here.

**Comment by Pranav-Saraswat** [comment]
buddy send me logs what error you facing ?

**Comment by KSKOP69** [comment]
> buddy send me logs what error you facing ?

bro this is not a error.
see this ss again.

**Comment by KSKOP69** [comment]
> buddy send me logs what error you facing ?

why auth users are coming there ?

**Comment by Pranav-Saraswat** [comment]
ohh now you clear my doubt got it soon I'll fix it

**Comment by KSKOP69** [comment]
> ohh now you clear my doubt got it soon I'll fix it

when fixing ?
