### ISSUE TITLE
Lefting VC

### ISSUE THREAD

**Issue by KSKOP69** [Pranav-Saraswat/YukkiMusicFork#37]
`Bot has left voice chat due to inactivity to avoid overload on servers. No-one was listening to the bot on voice chat.
`
Bot is lefting vc without playing full song

**Comment by KSKOP69** [comment]
still not fixed

**Comment by Pranav-Saraswat** [comment]
@KSKOP69 report to laky

**Comment by KSKOP69** [comment]
> @KSKOP69 report to laky

already done 

https://t.me/pytgcallschat/73211

**Comment by Pranav-Saraswat** [comment]
btw its a ffmpeg issue

**Comment by KSKOP69** [comment]
> btw its a ffmpeg issue

working fine before this [ update ](https://github.com/pytgcalls/pytgcalls/commit/df0f554e111eb71fb49d683494b6f95e59d1d8ef)
